###############################################################################
# Secrets Manager
#
# Two secrets:
#   - db:  RDS master credentials + DB host (rotated by RDS in real life)
#   - app: app-level secrets (JWT_SECRET, Square keys)
#
# Both are read at boot by the EC2 user-data and at runtime by Lambda.
# The DB password is generated by Terraform (random_password) so it's never
# hardcoded; the JWT secret is generated the same way on first apply.
###############################################################################

resource "random_password" "db_master" {
  length      = 32
  special     = false # avoids MySQL identifier-quoting headaches
  min_lower   = 4
  min_upper   = 4
  min_numeric = 4
}

resource "random_password" "jwt" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "db" {
  name                    = "${local.name_prefix}/db"
  description             = "RDS master credentials + connection info"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_master.result
    engine   = "mysql"
    host     = aws_db_instance.main.address
    port     = aws_db_instance.main.port
    dbname   = var.db_name
  })
}

resource "aws_secretsmanager_secret" "app" {
  name                    = "${local.name_prefix}/app"
  description             = "Application secrets (JWT, Square keys, etc.)"
  recovery_window_in_days = 7
}

# Note the placeholder values: Square keys are loaded from var.square_access_token
# at first apply but the operator typically rotates them in the console afterward.
# Terraform's `lifecycle.ignore_changes` keeps that rotation from being clobbered.
resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id
  secret_string = jsonencode({
    JWT_SECRET          = random_password.jwt.result
    SQUARE_ACCESS_TOKEN = var.square_access_token
    SQUARE_LOCATION_ID  = var.square_location_id
    SQUARE_ENVIRONMENT  = var.square_environment
  })

  lifecycle {
    # Once written, allow out-of-band rotation in the Secrets Manager console.
    ignore_changes = [secret_string]
  }
}
