#!/usr/bin/env bash
#
# Frontend tier setup — nginx that:
#   - Serves the static Front-End/ files directly from disk (fast, cached).
#   - Reverse-proxies /api/, /healthz, /readyz to one or more backend nodes.
#   - Provides its own /nginx-health for the ALB target group on the nginx tier.
#
# When you put this script behind an AWS Application Load Balancer in two or
# more AZs, you get redundancy: any one nginx node can disappear and the ALB
# routes around it; nginx itself load-balances across all configured backend
# nodes with health-aware upstreams.
#
# Required env vars (one of):
#   BACKEND_HOST  Single backend host:port (e.g. 10.0.5.10:3000)
#   BACKEND_HOSTS Comma-separated list (e.g. 10.0.5.10:3000,10.0.5.11:3000)
#
# Optional:
#   SERVER_NAME              default: _
#   FRONTEND_PATH            default: /var/www/sparko
#   CLOUDWATCH_LOG_GROUP     default: /sparko/web

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/common.sh"

SERVER_NAME="${SERVER_NAME:-_}"
FRONTEND_PATH="${FRONTEND_PATH:-/var/www/sparko}"
BACKEND_HOST="${BACKEND_HOST:-}"
BACKEND_HOSTS="${BACKEND_HOSTS:-}"
CLOUDWATCH_LOG_GROUP="${CLOUDWATCH_LOG_GROUP:-/sparko/web}"
SERVICE_NAME="nginx"

resolve_backends() {
    # Build a multi-line "server …;" block for the nginx upstream.
    # `max_fails=3 fail_timeout=30s` means a flaky backend gets ejected from
    # the pool automatically — that is the redundancy we want when sitting
    # behind the ALB with multiple API instances.
    local list="${BACKEND_HOSTS:-${BACKEND_HOST}}"
    if [[ -z "$list" ]]; then
        die "Set BACKEND_HOST or BACKEND_HOSTS (comma-separated host:port list)."
    fi
    UPSTREAM_BLOCK=""
    IFS=',' read -r -a hosts <<<"$list"
    for h in "${hosts[@]}"; do
        h="$(echo "$h" | xargs)"  # trim
        [[ -z "$h" ]] && continue
        UPSTREAM_BLOCK+="    server ${h} max_fails=3 fail_timeout=30s;"$'\n'
    done
    log "Upstreams resolved:"
    printf '%s' "$UPSTREAM_BLOCK"
}

install_nginx() {
    pkg_install nginx rsync curl
    systemctl enable nginx
}

deploy_static_files() {
    if [[ ! -d "${REPO_DIR}/Front-End" ]]; then
        die "Front-End directory missing at ${REPO_DIR}/Front-End"
    fi
    install -d -m 0755 "${FRONTEND_PATH}"
    log "Deploying static files to ${FRONTEND_PATH}…"
    rsync -a --delete \
        --exclude='.DS_Store' \
        "${REPO_DIR}/Front-End/" "${FRONTEND_PATH}/"
    chown -R nginx:nginx "${FRONTEND_PATH}" 2>/dev/null \
        || chown -R www-data:www-data "${FRONTEND_PATH}" 2>/dev/null \
        || true
}

write_nginx_config() {
    local conf_dir
    if [[ -d /etc/nginx/conf.d ]]; then
        conf_dir=/etc/nginx/conf.d
    else
        die "Unexpected nginx layout — /etc/nginx/conf.d not found."
    fi

    # Disable Amazon Linux's default placeholder vhost when present so our
    # config is the only server on port 80.
    if [[ -f /etc/nginx/nginx.conf ]] && grep -q 'server {' /etc/nginx/nginx.conf; then
        # Amazon Linux ships a default server inside nginx.conf — comment it
        # out to avoid duplicate default_server warnings on reload.
        sed -i 's/^\(\s*\)default_server/\1# default_server # disabled by sparko setup/' /etc/nginx/nginx.conf || true
    fi

    cat >"${conf_dir}/sparko.conf" <<NGINX
# ----------------------------------------------------------------------------
# Sparko Water — nginx config
# Generated by setup/frontend-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ----------------------------------------------------------------------------

# Backend pool. nginx will load-balance round-robin and skip a node that fails
# 3 times in 30 seconds — this is the application-level redundancy that
# complements the ALB sitting in front of the nginx tier.
upstream sparko_api {
${UPSTREAM_BLOCK}    keepalive 32;
}

# Real client IP from the upstream ALB. The ALB writes the original client IP
# into X-Forwarded-For; we trust the VPC CIDR ranges that the ALB sits inside.
# Adjust 'set_real_ip_from' to your VPC CIDR for tighter trust.
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.16.0.0/12;
set_real_ip_from 192.168.0.0/16;
real_ip_header   X-Forwarded-For;
real_ip_recursive on;

# Use the original protocol when the ALB terminates TLS.
map \$http_x_forwarded_proto \$forwarded_proto {
    default \$scheme;
    https   https;
    http    http;
}

# Structured-ish access log line — easy to parse in CloudWatch.
log_format sparko_json escape=json
    '{'
        '"ts":"\$time_iso8601",'
        '"client":"\$remote_addr",'
        '"method":"\$request_method",'
        '"uri":"\$request_uri",'
        '"status":\$status,'
        '"bytes":\$body_bytes_sent,'
        '"rt":\$request_time,'
        '"ua":"\$http_user_agent",'
        '"xff":"\$http_x_forwarded_for",'
        '"reqid":"\$http_x_request_id",'
        '"upstream":"\$upstream_addr",'
        '"upstream_rt":"\$upstream_response_time"'
    '}';

server {
    listen 80 default_server;
    server_name ${SERVER_NAME};

    root ${FRONTEND_PATH};
    index index.html;

    access_log /var/log/nginx/access.log sparko_json;
    error_log  /var/log/nginx/error.log warn;

    # ALB target-group health check for the nginx tier itself.
    location = /nginx-health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\\n";
    }

    # ---- API + backend health passthroughs ----
    location /api/ {
        proxy_pass         http://sparko_api;
        proxy_http_version 1.1;
        proxy_set_header   Connection        "";
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$forwarded_proto;
        proxy_set_header   X-Request-Id      \$request_id;
        proxy_read_timeout 30s;
        proxy_connect_timeout 5s;

        # If an upstream dies mid-request, retry the next one — application-
        # level redundancy on top of nginx's passive ejection.
        proxy_next_upstream     error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
    }

    location = /healthz { proxy_pass http://sparko_api; access_log off; }
    location = /readyz  { proxy_pass http://sparko_api; }

    # ---- Static assets ----
    location ~* \\.(?:css|js|svg|ttf|woff2?|png|jpg|jpeg|gif|ico)\$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        try_files \$uri =404;
    }

    # SPA-ish fallback: any unknown path serves index.html so client-side
    # routing still works.
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Security headers (the API also emits these via helmet, but having them
    # here covers static HTML/CSS/JS responses too).
    add_header X-Content-Type-Options nosniff       always;
    add_header X-Frame-Options        SAMEORIGIN     always;
    add_header Referrer-Policy        no-referrer-when-downgrade always;
}
NGINX

    nginx -t
    systemctl restart nginx
    log "nginx reloaded with new config."
}

install_cw_agent_for_web() {
    log "Installing CloudWatch agent for nginx access/error logs…"
    SERVICE_NAME="nginx" CLOUDWATCH_LOG_GROUP="${CLOUDWATCH_LOG_GROUP}" \
        bash "${SCRIPT_DIR}/cloudwatch-agent.sh"
}

configure_firewall() {
    if systemctl is-active --quiet firewalld 2>/dev/null; then
        log "Opening 80/tcp via firewalld…"
        firewall-cmd --permanent --add-service=http
        firewall-cmd --reload
    fi
}

health_check() {
    log "Waiting for /nginx-health…"
    for i in {1..20}; do
        if curl -fsS "http://127.0.0.1/nginx-health" >/dev/null 2>&1; then
            log "nginx is responding."
            break
        fi
        sleep 1
    done

    log "Probing upstream /healthz through nginx…"
    if curl -fsS "http://127.0.0.1/healthz" >/dev/null 2>&1; then
        log "Upstream is reachable."
    else
        warn "Upstream /healthz failed — verify BACKEND_HOST(S) and that the SG allows nginx→API on port 3000."
    fi
}

print_summary() {
    cat <<EOF

============================================================
  Sparko frontend tier setup complete
============================================================
  Listening on:        0.0.0.0:80
  Static root:         ${FRONTEND_PATH}
  Upstream backends:
$(printf '    %s\n' $(echo "$UPSTREAM_BLOCK" | grep -oE 'server [^;]+' | sed 's/^server //'))
------------------------------------------------------------
  ALB target group settings for THIS tier:
      Health check path  : /nginx-health
      Traffic port       : 80
      Healthy threshold  : 2
      Unhealthy threshold: 3
------------------------------------------------------------
  Logs:
      Local:  /var/log/nginx/{access,error}.log
      Cloud:  CloudWatch group ${CLOUDWATCH_LOG_GROUP}/nginx
============================================================
EOF
}

main() {
    ensure_root "$@"
    detect_os
    resolve_backends
    install_nginx
    deploy_static_files
    write_nginx_config
    install_cw_agent_for_web
    configure_firewall
    health_check
    print_summary
}

main "$@"
